version: "3"

services:
  base-node:
    image: ubuntu:22.04
    container_name: base-node
    restart: unless-stopped

    ports:
      - "30303:30303"

    volumes:
      - ./data:/data

    command: tail -f /dev/null
