name: Markdown Check

on:
  push:
    branches:
      - main

jobs:
  markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Markdown Lint
        run: echo "Markdown checked"
